CREATE TABLE [dbo].[EventAttendance]
(
[Id] UNIQUEIDENTIFIER NOT NULL,
	[EventId] UNIQUEIDENTIFIER NOT NULL , 
    [StudentId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK_EventAttendance] PRIMARY KEY ([Id])
)
