CREATE TABLE [dbo].[Events]
(
	[EventID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [EventName] VARCHAR(MAX) NOT NULL, 
    [EventLocation] VARCHAR(100) NOT NULL, 
    [EventStart] DATETIME NOT NULL, 
    [EventEnd] DATETIME NOT NULL
)
