CREATE TABLE [dbo].[Events]
(
	[EventID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [EventName] VARCHAR(MAX) NOT NULL, 
    [EventLocation] VARCHAR(100) NOT NULL, 
    [EventStart] DATETIME NOT NULL, 
    [EventEnd] DATETIME NOT NULL, 
    [CreatedBy] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_EVENTS_USER] FOREIGN KEY (CreatedBy)
	REFERENCES Users(UserID)
	ON DELETE CASCADE
	ON UPDATE CASCADE 
)
